version: '3.7'

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vt-server-img
    container_name: vt-node-express
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB